[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Build completed'"
]

[start]
cmd = "cd backend && python3 server.py" 