[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python3 server.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHONPATH = "./backend" 