[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python server.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHONPATH = "backend"

[variables]
PORT = "5001" 